name: CupertinoToolbar
description: Cupertino Toolbar example app

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  cupertino_toolbar: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: